### PR TITLE
Add :reverse option to change page_title_symbol position

### PR DESCRIPTION
**Pull request by kriskhaira**
All tests pass. Also updated the README.

### CODE REVIEW

**Comment by lenart** [comment]
:+1: 

Any reasons why this request was not merged yet?

**Comment by mjankowski** [comment]
Thanks for the ping.

Two reasons:

* I'm considering removed the page_title method from flutie entirely, in favor of pointing people at the "title" gem instead
* I'd prefer if this implementation used true/false instead of 1/0 (even though it works the same with ruby)

Sorry about lack of feedback here!

**Comment by lenart** [comment]
Thanks for the explanation. If the plan is to leave out handling of title tag then it's ok. Maybe you should put this in the gem description so other users (like myself) will stop bugging you and switch to the title gem.

**Comment by nfedyashev** [comment]
@kriskhaira thanks for the pull request!
Until this is merged I'm going with your fork.

**Comment by mjankowski** [comment]
Support for this was added in version 2.1.0

**Pull request closed without merging**
